version: "3.3"
services:

  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ../../app:/app
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=r00tp455sword19970225
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes: 
      - ../database:/var/lib/mysql
