version: "3.3"
services:

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - db
    env_file:
      - .env
    container_name: backend
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/backend
    # expose:
    #   - 8000
    # Comentar PORTS caso executar com o frontend: http://localhost:8000/docs
    ports:
      - "8000:8000"

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/:/frontend
  #   ports:
  #     - 80:80

  db:
    container_name: database
    image: mariadb
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes: 
      - ../database:/var/lib/mysql
  
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes: 
  #     - ../redis:/data
